### ISSUE TITLE
Update to Akka 2.5

### ISSUE THREAD

**Issue by johanandren** [akka/hello-akka.g8#2]

**Comment by patriknw** [comment]
How does g8 work with branches? I see that https://github.com/akka/akka-scala-seed.g8 has a `2.4` branch as default branch. @eed3si9n ?

**Comment by johanandren** [comment]
Noticed that as well after working continuing from this one onto that repo and seeing that it actually does not contain an Akka version at all.

**Comment by eed3si9n** [comment]
Giter8 takes `-b` option to specify branches. Otherwise it should use the default branch specified on the repo.

**Comment by johanandren** [comment]
Closing this PR and setting those branches up then.
